#!/usr/bin/env python3
"""Generate messages/{locale}.json for every official EU language."""
from __future__ import annotations

import copy
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN = json.loads((ROOT / "messages" / "en.json").read_text())

LOCALES = [
    "bg", "cs", "da", "de", "el", "es", "et", "fi", "fr", "ga", "hr", "hu",
    "it", "lt", "lv", "mt", "nl", "pl", "pt", "ro", "sk", "sl", "sv",
]


def deep_merge(base: dict, overlay: dict) -> dict:
    out = copy.deepcopy(base)
    for k, v in overlay.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def unflatten(flat: dict[str, str]) -> dict:
    root: dict = {}
    for path, value in flat.items():
        cur = root
        parts = path.split(".")
        for p in parts[:-1]:
            cur = cur.setdefault(p, {})
        cur[parts[-1]] = value
    return root


# Full nested catalogs for DE/FR (public + member chrome).
T: dict[str, dict] = {}

T["de"] = {
  "meta": {"title": "ERBA – Europäische Allianz gegen Regulierungslast", "description": "Europas Realwirtschaft hat genug. Schließen Sie sich der Bewegung an, die die wahren Kosten kumulativer EU-Regulierung misst.", "joinTitle": "Kostenlos beitreten – Regulierungslast eintragen", "joinDescription": "Registrieren Sie Ihr Unternehmen und erfassen Sie die jährlichen Kosten Ihrer schwersten EU-Regulierungslast. Anonyme Option verfügbar.", "loginTitle": "Anmelden", "loginDescription": "Melden Sie sich im ERBA-Mitgliederbereich an.", "painIndexTitle": "Der Pain Index – Dokumentierte Kosten der EU-Regulierung", "painIndexDescription": "Live erhobene jährliche Compliance-Kosten europäischer Mid-Cap-Unternehmen, aufgeschlüsselt nach Regulierung.", "dashboardTitle": "Mitgliederbereich"},
  "nav": {"painIndex": "Pain Index", "whyNow": "Warum jetzt", "join": "Kostenlos beitreten", "login": "Anmelden", "dashboard": "Dashboard", "signOut": "Abmelden", "language": "Sprache", "menu": "Navigation umschalten", "alliance": "Europäische Allianz gegen Regulierungslast"},
  "footer": {"blurb": "Ein unabhängiger Zusammenschluss von Mid-Cap-CEOs, der die kumulativen Kosten der EU-Regulierung dokumentiert – Datenpunkt für Datenpunkt.", "platform": "Plattform", "campaigns": "Kampagnen", "contact": "Kontakt", "memberDashboard": "Mitgliederbereich", "farmerProtests": "Bauernproteste", "greenDeal": "Green-Deal-Druck", "mercosur": "Mercosur-Bedrohung", "rights": "Alle Rechte vorbehalten.", "anonymousNote": "Anonyme Meldungen werden niemals einem namentlich genannten Unternehmen zugeordnet.", "cities": "Brüssel · Berlin · Paris"},
  "landing": {"badge": "Bewegung offen für Mid-Cap-CEOs", "headlineBefore": "Europas Realwirtschaft hat", "headlineAccent": "genug.", "subhead": "Kumulierte EU-Regulierung tötet die Wettbewerbsfähigkeit. Schließen Sie sich der Bewegung an, die die realen Kosten misst.", "ctaJoin": "Kostenlos beitreten – Regulierungslast eintragen", "ctaPain": "Pain Index ansehen", "noFees": "Keine Gebühren. Kein Lobbybudget nötig. Anonyme Option verfügbar.", "companiesJoined": "Beigetretene Unternehmen", "documentedCosts": "Dokumentierte Compliance-Kosten", "whyNowEyebrow": "Warum jetzt", "whyNowTitle": "Das Fenster für einen Kurswechsel schließt sich.", "whyNowLead": "Drei Kräfte sind in den letzten 18 Monaten zusammengetroffen. Gemeinsam machen sie das Schweigen teurer als das Sprechen.", "farmerTitle": "Bauernproteste", "farmerBody": "Traktoren blockierten Brüssel, Paris und Berlin. Landwirte haben bewiesen: Wenn die Realwirtschaft gemeinsam Druck macht, hört die Kommission zu. Mid-Caps haben ihre Stimme noch nicht erhoben.", "greenTitle": "Green-Deal-Druck", "greenBody": "CSRD, CSDDD, EUDR, CBAM, die Taxonomie. Jede Regel allein wirkt 'machbar'. Übereinander gelegt binden sie ganze Finanz- und Rechtsteams in global konkurrierenden Unternehmen.", "mercosurTitle": "Mercosur-Bedrohung", "mercosurBody": "Handelsabkommen öffnen die Tür für Wettbewerber ohne diese Pflichten. Europa exportiert seine industrielle Basis und importiert Waren unter leichteren Regeln.", "howEyebrow": "So funktioniert es", "howTitle": "Eine Zahl, der Brüssel nicht widersprechen kann.", "howLead": "Anekdoten werden abgetan. Aggregierte, nachprüfbare Kostendaten von Tausenden Unternehmen nicht. ERBA macht aus Ihrem Compliance-Problem einen Tagesordnungspunkt.", "howCta": "Regulierungslast eintragen", "step1Title": "Unternehmen registrieren", "step1Body": "Zwei Minuten. Auf Wunsch anonym.", "step2Title": "Compliance-Kosten erfassen", "step2Body": "Wählen Sie die schmerzhafteste Regulierung und schätzen Sie die Jahreslast.", "step3Title": "Die Zahl verstärken", "step3Body": "Ihre Daten speisen den öffentlichen Pain Index, den Politik nicht ignorieren kann.", "closeTitle": "Ihre Compliance-Kosten sind eine politische Tatsache.", "closeAccent": "Lassen Sie sie zählen.", "closeLead": "Schließen Sie sich {count} Unternehmen an, die bereits erfasst sind. Das dauert weniger als das Lesen einer CSRD-Angabe."},
  "join": {"eyebrow": "Der Allianz beitreten", "title": "Tragen Sie Ihre Compliance-Kosten ins Register ein.", "lead": "{count} Unternehmen haben bereits {cost} an Regulierungslast dokumentiert. Jeder neue Datenpunkt macht die Zahl schwerer zu ignorieren.", "twoMinTitle": "Zwei Minuten", "twoMinBody": "Drei kurze Schritte. Keine Unterlagen nötig.", "anonTitle": "Anonyme Option", "anonBody": "Ihre Kosten zählen; der Unternehmensname kann verborgen bleiben.", "neverTitle": "Niemals verkauft", "neverBody": "Daten nur für Advocacy aggregiert, nie an Anbieter weitergegeben.", "loading": "Formular wird geladen"},
  "login": {"eyebrow": "Mitgliederzugang", "title": "Willkommen zurück", "lead": "Melden Sie sich an, um War Room, Checklisten und Empfehlungstracker zu nutzen.", "subtitle": "Melden Sie sich an, um den War Room und Ihren Empfehlungstracker zu nutzen.", "email": "E-Mail", "password": "Passwort", "submit": "Anmelden", "submitting": "Anmeldung…", "failed": "Anmeldung fehlgeschlagen", "newTo": "Neu bei ERBA?", "joinFree": "Kostenlos beitreten", "confirmationFailed": "Dieser Bestätigungslink ist ungültig oder abgelaufen. Melden Sie sich unten an oder fordern Sie durch erneute Registrierung einen neuen Link an.", "notConfigured": "Diese Instanz ist noch nicht mit Supabase verbunden. Setzen Sie NEXT_PUBLIC_SUPABASE_URL und NEXT_PUBLIC_SUPABASE_ANON_KEY.", "genericError": "Anmeldung nicht möglich. Prüfen Sie Ihre Zugangsdaten."},
  "wizard": {"step": "Schritt {current} von {total}", "account": "Konto", "accountWho": "Wer Sie sind", "company": "Unternehmen", "companyWhat": "Was Sie führen", "pain": "Pain Index", "painWhat": "Was es kostet", "fullName": "Vollständiger Name", "workEmail": "Geschäftliche E-Mail", "password": "Passwort", "emailHint": "E-Mail-Adressen werden niemals veröffentlicht.", "passwordHint": "Mindestens 8 Zeichen, inklusive Buchstabe und Zahl.", "companyName": "Unternehmensname", "industry": "Branche", "turnover": "Jahresumsatz", "selectIndustry": "Branche wählen", "selectTurnover": "Umsatzklasse wählen", "anonymous": "Unternehmen anonym halten", "anonymousHint": "Ihre Kostendaten zählen im Pain Index, der Name erscheint nie öffentlich.", "regulation": "Schwerste Regulierungslast", "selectRegulation": "Wählen Sie die schmerzhafteste Regulierung", "cost": "Geschätzte jährliche Compliance-Kosten (EUR)", "costHint": "Inklusive Personal, Berater, Audits, Software und Rechtskosten.", "describe": "Die Last beschreiben", "optional": "Optional", "continue": "Weiter", "back": "Zurück", "submit": "Der Allianz beitreten", "creating": "Konto wird erstellt…", "alreadyMember": "Bereits Mitglied?", "signIn": "Anmelden", "referralApplied": "Empfehlung übernommen", "referralCode": "Sie wurden mit Code {code} eingeladen.", "confirmTitle": "E-Mail bestätigen", "confirmBody": "Unternehmen und Regulierungslast sind erfasst. Wir haben einen Bestätigungslink an {email} gesendet. Klicken Sie ihn, um das Dashboard freizuschalten.", "viewPain": "Pain Index ansehen", "confirmedSignIn": "Bestätigt – anmelden", "errorTitle": "Registrierung nicht abgeschlossen", "duplicate": "Ein Konto mit dieser E-Mail existiert bereits. Bitte anmelden.", "placeholderName": "Maria Schneider", "placeholderEmail": "ceo@ihrunternehmen.eu", "placeholderCompany": "Schneider Präzisionstechnik GmbH", "placeholderCost": "250000", "placeholderDescription": "z. B. Zwei Vollzeitstellen verbringen 60 % ihrer Zeit mit Doppelwesentlichkeit und Lieferantenfragebögen.", "accountDetails": "Kontodaten", "companyDetails": "Unternehmensdaten", "painDetails": "Regulierungslast", "progress": "Fortschritt", "genericError": "Beim Erstellen des Kontos ist etwas schiefgelaufen. Bitte erneut versuchen.", "noUser": "Registrierung erfolgreich, aber kein Benutzer zurückgegeben."},
  "validation": {"fullName": "Bitte geben Sie Ihren vollständigen Namen ein", "nameLong": "Name ist zu lang", "email": "Gültige geschäftliche E-Mail eingeben", "passwordShort": "Passwort muss mindestens 8 Zeichen haben", "passwordLong": "Passwort ist zu lang", "passwordLetter": "Passwort muss einen Buchstaben enthalten", "passwordNumber": "Passwort muss eine Zahl enthalten", "companyName": "Bitte Unternehmensnamen eingeben", "companyLong": "Unternehmensname ist zu lang", "industry": "Branche wählen", "turnover": "Umsatzklasse wählen", "regulation": "Wählen Sie die schmerzhafteste Regulierung", "cost": "Geschätzte Jahreskosten in EUR eingeben", "costPositive": "Kosten müssen größer als null sein", "costLarge": "Diese Zahl wirkt zu groß", "descriptionLong": "Beschreibung unter 1.000 Zeichen halten", "passwordRequired": "Passwort eingeben"},
  "industries": {"Manufacturing": "Verarbeitendes Gewerbe", "Agriculture & Food": "Landwirtschaft & Lebensmittel", "Automotive": "Automobil", "Chemicals": "Chemie", "Construction": "Bau", "Energy & Utilities": "Energie & Versorgung", "Logistics & Transport": "Logistik & Transport", "Retail & Wholesale": "Einzel- & Großhandel", "Textiles & Apparel": "Textil & Bekleidung", "Technology & Software": "Technologie & Software", "Pharma & Medical Devices": "Pharma & Medizinprodukte", "Financial Services": "Finanzdienstleistungen", "Other": "Sonstiges"},
  "regulations": {"CSRD": "CSRD (Richtlinie zur Nachhaltigkeitsberichterstattung)", "Supply Chain Act": "Lieferkettengesetz (CSDDD)", "Deforestation": "Entwaldungsverordnung (EUDR)", "Other": "Sonstiges"},
  "painIndex": {"badge": "Live · Crowdsourced · Anonymisiert", "title": "Der Pain Index", "lead": "Jährliche Compliance-Kosten europäischer Unternehmen, Regulierung für Regulierung.", "documented": "Dokumentierte jährliche Regulierungslast", "approx": "≈ {compact} pro Jahr, über {submissions} {submissionLabel} von {companies} {companyLabel}", "submission": "Meldung", "submissions": "Meldungen", "company": "Unternehmen", "companies": "Unternehmen", "companiesReporting": "Meldende Unternehmen", "averageCost": "Durchschnittskosten je Meldung", "latest": "Letzter Datenpunkt", "unavailableTitle": "Livedaten nicht verfügbar", "leaderboard": "Rangliste", "leaderboardTitle": "Welche Regulierung kostet Europa am meisten?", "ranked": "Nach dokumentierten Jahreskosten", "perYear": "pro Jahr", "emptyTitle": "Noch keine Meldungen", "emptyBody": "Der Pain Index beginnt mit dem ersten Unternehmen, das eine Zahl nennt. Seien Sie der erste Datenpunkt.", "addData": "Daten hinzufügen", "method": "Methodik: selbst gemeldete jährliche Compliance-Kostenschätzungen von Mitgliedsunternehmen. Unternehmensidentitäten werden nie angezeigt; anonyme Meldungen fließen in Aggregate ein. Summen werden jede Minute aktualisiert.", "cta": "Trifft Ihr Unternehmen diese Kosten?", "ctaAnon": "Daten anonym hinzufügen.", "ctaButton": "Regulierungslast eintragen", "ofTotal": "{percent} % der Gesamtsumme"},
  "dashboardNav": {"overview": "Überblick", "overviewDesc": "War Room & Empfehlungen", "policy": "Policy-Dashboard", "policyShort": "Policy", "policyDesc": "Regulatorischer Intelligence-Feed", "checklists": "Compliance-Checklisten", "checklistsShort": "Checklisten", "checklistsDesc": "Pflichten nach Branche", "vault": "Dokumentenarchiv", "vaultShort": "Archiv", "vaultDesc": "Zertifikate & Nachweise", "forum": "Netzwerk-Hub", "forumShort": "Hub", "forumDesc": "Strategieaustausch der Mitglieder", "noCompany": "Noch kein Unternehmen", "completeOnboarding": "Onboarding abschließen", "anonymous": "Anonym", "verified": "Verifiziert", "rlsNote": "Unternehmensdaten sind durch Postgres-Row-Level-Security geschützt. Nur Mitglieder Ihrer Organisation können Aufgaben und Dokumente lesen."},
  "dashboard": {"overview": "Überblick", "welcome": "Willkommen in der Allianz", "publicPain": "Öffentlicher Pain Index", "warRoom": "The War Room", "liveCampaign": "Live-Kampagne", "contributions": "Ihre Pain-Index-Beiträge", "addCompany": "Unternehmen hinzufügen", "noSubmissions": "Noch keine Regulierungslast erfasst.", "addFirst": "Erste Meldung hinzufügen", "referral": "Empfehlungstracker", "membershipIncludes": "Vollmitgliedschaft umfasst", "perk1": "Vierteljährliche MEP-Briefings mit dem ERBA-Policy-Team", "perk2": "Den Cumulative Burden Report vor der öffentlichen Freigabe", "perk3": "Einen Platz in der jährlichen Brüsseler CEO-Delegation", "perk4": "Widerspruchsvorlagen für jeden neuen Green-Deal-Rechtsakt", "submission": "Meldung", "submissions": "Meldungen", "totalBurden": "Dokumentierte Gesamtlast:", "perYear": "pro Jahr", "perYearShort": "/Jahr", "unknownCompany": "Unbekanntes Unternehmen", "ourCompany": "Unser Unternehmen", "completeOnboarding": "Onboarding abschließen"},
  "notFound": {"title": "Seite nicht gefunden", "body": "Die Regulierung mag endlos sein – diese URL ist es nicht. Zurück zur Bewegung.", "home": "Zur Startseite", "join": "Kostenlos beitreten"},
}

T["fr"] = {
  "meta": {"title": "ERBA – Alliance européenne contre la charge réglementaire", "description": "L'économie réelle européenne en a assez. Rejoignez le mouvement qui mesure le coût réel de la régulation cumulative de l'UE.", "joinTitle": "Rejoindre gratuitement – Ajoutez votre charge réglementaire", "joinDescription": "Enregistrez votre entreprise et le coût annuel de votre plus lourde charge réglementaire UE. Option anonyme disponible.", "loginTitle": "Connexion", "loginDescription": "Connectez-vous à l'espace membres ERBA.", "painIndexTitle": "Le Pain Index – Coût documenté de la régulation UE", "painIndexDescription": "Total en direct des coûts de conformité annuels déclarés par les mid-caps européennes, par réglementation.", "dashboardTitle": "Espace membres"},
  "nav": {"painIndex": "Pain Index", "whyNow": "Pourquoi maintenant", "join": "Rejoindre gratuitement", "login": "Connexion", "dashboard": "Tableau de bord", "signOut": "Déconnexion", "language": "Langue", "menu": "Ouvrir la navigation", "alliance": "Alliance européenne contre la charge réglementaire"},
  "footer": {"blurb": "Une coalition indépendante de PDG de mid-caps qui documente le coût cumulé de la régulation européenne, point de données après point de données.", "platform": "Plateforme", "campaigns": "Campagnes", "contact": "Contact", "memberDashboard": "Espace membres", "farmerProtests": "Protestations agricoles", "greenDeal": "Pression du Pacte vert", "mercosur": "Menace Mercosur", "rights": "Tous droits réservés.", "anonymousNote": "Les déclarations anonymes ne sont jamais attribuées à une entreprise nommée.", "cities": "Bruxelles · Berlin · Paris"},
  "landing": {"badge": "Mouvement ouvert aux PDG de mid-caps", "headlineBefore": "L'économie réelle européenne en a", "headlineAccent": "assez.", "subhead": "La régulation cumulative de l'UE tue la compétitivité. Rejoignez le mouvement qui mesure le vrai coût.", "ctaJoin": "Rejoindre gratuitement – Ajoutez votre charge réglementaire", "ctaPain": "Voir le Pain Index", "noFees": "Gratuit. Pas de budget de lobbying. Option anonyme disponible.", "companiesJoined": "Entreprises inscrites", "documentedCosts": "Coûts de conformité documentés", "whyNowEyebrow": "Pourquoi maintenant", "whyNowTitle": "La fenêtre pour changer de cap se referme.", "whyNowLead": "Trois forces ont convergé en 18 mois. Ensemble, elles rendent le silence plus coûteux que la parole.", "farmerTitle": "Protestations agricoles", "farmerBody": "Des tracteurs ont bloqué Bruxelles, Paris et Berlin. Les agriculteurs ont prouvé que lorsque l'économie réelle pousse ensemble, la Commission écoute. Les mid-caps n'ont pas encore fait entendre leur voix.", "greenTitle": "Pression du Pacte vert", "greenBody": "CSRD, CSDDD, EUDR, CBAM, la taxonomie. Chaque règle seule paraît 'gérable'. Empilées, elles absorbent des équipes finance et juridique entières.", "mercosurTitle": "Menace Mercosur", "mercosurBody": "Les accords commerciaux ouvrent la porte à des concurrents sans ces obligations. L'Europe exporte sa base industrielle et importe des biens produits sous des règles plus légères.", "howEyebrow": "Comment ça marche", "howTitle": "Un chiffre que Bruxelles ne peut pas contester.", "howLead": "Les anecdotes sont écartées. Des données de coût agrégées et vérifiables, non. ERBA transforme votre fardeau de conformité en point à l'ordre du jour.", "howCta": "Ajouter votre charge réglementaire", "step1Title": "Enregistrez votre entreprise", "step1Body": "Deux minutes. Anonyme si vous le souhaitez.", "step2Title": "Enregistrez le coût de conformité", "step2Body": "Choisissez la réglementation la plus lourde et estimez la charge annuelle.", "step3Title": "Amplifiez le chiffre", "step3Body": "Vos données alimentent le Pain Index public que les décideurs ne peuvent ignorer.", "closeTitle": "Votre coût de conformité est un fait politique.", "closeAccent": "Faites-le compter.", "closeLead": "Rejoignez {count} entreprises déjà enregistrées. Cela prend moins de temps que de lire une exigence CSRD."},
  "join": {"eyebrow": "Rejoindre l'Alliance", "title": "Inscrivez le coût de votre conformité.", "lead": "{count} entreprises ont déjà documenté {cost} de charge réglementaire. Chaque nouveau point rend le chiffre plus difficile à écarter.", "twoMinTitle": "Deux minutes", "twoMinBody": "Trois étapes courtes. Aucun document requis.", "anonTitle": "Option anonyme", "anonBody": "Votre coût compte ; le nom de l'entreprise peut rester caché.", "neverTitle": "Jamais vendu", "neverBody": "Données agrégées pour le plaidoyer uniquement, jamais partagées avec des vendeurs.", "loading": "Chargement du formulaire"},
  "login": {"eyebrow": "Accès membres", "title": "Bon retour", "lead": "Connectez-vous pour accéder à la salle de guerre, aux listes et au suivi de parrainage.", "subtitle": "Connectez-vous pour accéder à la salle de guerre et à votre suivi de parrainage.", "email": "E-mail", "password": "Mot de passe", "submit": "Connexion", "submitting": "Connexion…", "failed": "Échec de la connexion", "newTo": "Nouveau sur ERBA ?", "joinFree": "Rejoindre gratuitement", "confirmationFailed": "Ce lien de confirmation est invalide ou a expiré. Connectez-vous ci-dessous, ou inscrivez-vous à nouveau pour un nouveau lien.", "notConfigured": "Cette instance n'est pas encore connectée à Supabase. Définissez NEXT_PUBLIC_SUPABASE_URL et NEXT_PUBLIC_SUPABASE_ANON_KEY.", "genericError": "Impossible de vous connecter. Vérifiez vos identifiants."},
  "wizard": {"step": "Étape {current} sur {total}", "account": "Compte", "accountWho": "Qui vous êtes", "company": "Entreprise", "companyWhat": "Ce que vous dirigez", "pain": "Pain Index", "painWhat": "Ce que cela coûte", "fullName": "Nom complet", "workEmail": "E-mail professionnel", "password": "Mot de passe", "emailHint": "Nous ne publions jamais les adresses e-mail.", "passwordHint": "Au moins 8 caractères, dont une lettre et un chiffre.", "companyName": "Nom de l'entreprise", "industry": "Secteur", "turnover": "Chiffre d'affaires annuel", "selectIndustry": "Choisir un secteur", "selectTurnover": "Choisir une tranche de CA", "anonymous": "Garder mon entreprise anonyme", "anonymousHint": "Vos coûts comptent dans le Pain Index, le nom n'est jamais affiché publiquement.", "regulation": "Pire charge réglementaire", "selectRegulation": "Choisissez la réglementation la plus lourde", "cost": "Coût annuel estimé de conformité (EUR)", "costHint": "Incluez le temps interne, consultants, audits, logiciels et frais juridiques.", "describe": "Décrire la charge", "optional": "Facultatif", "continue": "Continuer", "back": "Retour", "submit": "Rejoindre l'Alliance", "creating": "Création du compte…", "alreadyMember": "Déjà membre ?", "signIn": "Connexion", "referralApplied": "Parrainage appliqué", "referralCode": "Vous avez été invité avec le code {code}.", "confirmTitle": "Confirmez votre e-mail", "confirmBody": "Votre entreprise et votre charge ont été enregistrées. Un lien de confirmation a été envoyé à {email}. Cliquez-le pour déverrouiller le tableau de bord.", "viewPain": "Voir le Pain Index", "confirmedSignIn": "J'ai confirmé – se connecter", "errorTitle": "Inscription incomplète", "duplicate": "Un compte existe déjà avec cet e-mail. Connectez-vous.", "placeholderName": "Marie Schneider", "placeholderEmail": "pdg@votreentreprise.eu", "placeholderCompany": "Schneider Precision SAS", "placeholderCost": "250000", "placeholderDescription": "ex. Deux ETP consacrent 60 % de leur temps aux questionnaires fournisseurs et à la double matérialité.", "accountDetails": "Coordonnées du compte", "companyDetails": "Détails de l'entreprise", "painDetails": "Charge réglementaire", "progress": "Progression", "genericError": "Impossible de créer le compte. Réessayez.", "noUser": "Inscription réussie mais aucun utilisateur renvoyé."},
  "notFound": {"title": "Page introuvable", "body": "La régulation peut être sans fin, cette URL ne l'est pas. Retournons au mouvement.", "home": "Accueil", "join": "Rejoindre gratuitement"},
}

# Remaining locales: public surface + login/join/wizard chrome.
PUBLIC = json.loads((ROOT / "scripts" / "locale-overlays.json").read_text()) if (ROOT / "scripts" / "locale-overlays.json").exists() else {}


def main() -> None:
    out_dir = ROOT / "messages"
    overlays_path = ROOT / "scripts" / "locale-overlays.json"
    extra = json.loads(overlays_path.read_text()) if overlays_path.exists() else {}

    for loc in LOCALES:
        overlay: dict = {}
        if loc in T:
            overlay = T[loc]
        if loc in extra:
            overlay = deep_merge(overlay, extra[loc])
        data = deep_merge(EN, overlay)
        (out_dir / f"{loc}.json").write_text(
            json.dumps(data, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print("wrote", loc)

    print("done", len(list(out_dir.glob("*.json"))), "files")


if __name__ == "__main__":
    main()
